version: '3.1'
services:
  stats-server:
    build: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat
      - SPRING_DATASOURCE_USER=Admin
      - SPRING_DATASOURCE_PASSWORD=123

  stat-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - ":5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=123

  ewm-service:
    build: ./ewm-service
    depends_on:
      - ewm-db
      - stat-db
    ports:
      - "8080:8080"
    environment:
      - STAT-SERVER_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=Admin
      - SPRING_DATASOURCE_PASSWORD=123

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - ":5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=123